---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an SQS Queue.
Parameters:
  QueueName:
    Type: String
    Default: DefaultQueue
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Join:
        - ''
        - - Ref: QueueName
          - "-@_!?"
          - Ref: AWS::StackName
Outputs:
  MyQueueARN:
    Value:
      Ref: MyQueue
